.:
  name: .
  description: 根目录，按照内容与来源分类
中国新闻网:
  name: 中国新闻网
  description: ''
凤凰网:
  name: 凤凰网
  description: ''
搜狐:
  name: 搜狐
  description: ''
新浪:
  name: 新浪
  description: ''
未分类:
  name: 未分类
  description: ''
澎湃:
  name: 澎湃
  description: ''
网易:
  name: 网易
  description: ''
腾讯:
  name: 腾讯
  description: ''
豆瓣:
  name: 豆瓣
  description: ''
