.:
  name: .
  description: 根目录，按照内容与来源分类
中国新闻网:
  name: 中国新闻网
  description: 本目录涉及多元性别主题的多篇报道，内容涵盖变性人、性别表现、儿童性心理等方面，展示了中性化以及性别多元化政策的发展。首先，讨论了韩国变性艺人河莉秀为改户口而向法院申请更改性别的经历，突显了个人与社会之间、公众形象与私生活之间的紧张关系；紧接着是四川泸州监察局调查官员公款观赏人妖表演事件的报道，揭示了公众对社会风气的强烈关注以及官员行为所引发的道德争议。之后，伦敦小学生交换妓女名片现象的报道引起了人们对儿童成长环境的担忧，政府对此的回应显示了社会和法律对性别暴露行为的态度。家庭背景对儿童性取向的影响也是本目录的一个重点，文章结合数据与心理学理论探讨性心理发展的复杂性，反映了社会对个体性取向误解的现状。同时，以日本女星中山美穗因丈夫的性别表现变化而引发的婚姻危机为例，进一步探讨现代婚姻中可能遇到的复杂性。除此之外，关于日本“伪娘”文化的分析展示了社会性别角色的演变，以及其对年轻人价值观的影响。最后，金色海岸变性人登记参选省议员的报导和美国海军解除对变性人服役禁令的消息，展现了多元性别群体在社会政治领域的新进展，体现了对变性人士权益的日渐重视与支持。
凤凰网:
  name: 凤凰网
  description: ''
搜狐:
  name: 搜狐
  description: 该目录包含多个关于多元性别和变性人群体的故事与报道，主要分为生命故事、社会现象和法律政策三个方面。首先，包括军事领域变性故事的汉纳·温特伯尔尼，她是英国陆军第一位变性军官，带领超过100名士兵，文章展示了她的内心挣扎与转变，以及在军队中获得的支持和接受；其次，搜狐视频栏目“人妖rose”收录了21个关于人妖rose的生活与工作的视频，探讨了她作为公众人物的影响力。此外，关于变性人兰的故事，影响深远，强调了社会认知的变迁，包括变性手术的个人故事、性别认同的挑战和希望等多样内容。最后，法律与社会环境方面的报道涉及了多位变性人的困境与挑战，以及韩国大法院关于变性人户籍性别更改的历史性判决，为变性人群体的权益保障提供了法律支持。全体故事反映了社会对多元性别的包容进程和对变性人群体的关注，促进了公众对这一特定群体的理解与接纳。
新浪:
  name: 新浪
  description: ''
未分类:
  name: 未分类
  description: ''
澎湃:
  name: 澎湃
  description: 目录《澎湃》包含多篇与多元性别相关的报道和个人故事，涵盖跨性别群体的生存状态、法律权益和社会环境等多个层面的内容。其中包括关于跨性别者的社会议题讨论，包括他们在求职中遭遇的隐性歧视，以及如何通过法律进行维权的报道，例如全国首例跨性别者平等就业权纠纷案的相关新闻。此外，还记录了关于跨性别者的心理状态与医疗需求的讨论，反映了变性人所面临的医疗和法律挑战。通过这些深入的文章和评论，目录展示了跨性别者在中国社会中复杂的生存现状及其对社会的影响，同时引发对性别权利和社会包容性的深入思考。
网易:
  name: 网易
  description: ''
腾讯:
  name: 腾讯
  description: 该目录包含来自腾讯媒介的一系列关于多元性别的作品与报道，涉及漫画、视频、新闻文章和文学作品等多种形式。《我的伪娘室友》是腾讯动漫发布的一部漫画作品，第九话描述了伪娘角色的生活细节和身份认同的探讨，以及人物间的互动与冲突。台湾影片《迷失安狄》的预告片展示了变性人在社会中的挑战，试图引发公众对多元性别的关注。腾讯新闻中的多篇文章探讨了男性穿女装的文化现象、校园霸凌事件下的性别问题，以及跨性别者的真实故事等，分析了社会、医学与文化对性别认同的影响。此外，目录中还有变装小说的推荐，通过轻松幽默的方式展现变装文化的多样性，反映当代社会对性别流动性的接纳与理解。这些内容共同丰富了关于多元性别的视角与表达，促进了对性别认同和性别角色的深入思考。
豆瓣:
  name: 豆瓣
  description: 目录《豆瓣》下的文件包括各种与多元性别相关的内容，其中有关于《魁拔之书》的读书笔记，探讨了书中呈现的同性恋和跨种族婚姻的道德观念，反映了文化和社会结构对性别认同的影响。另一本漫画《MARS
    6》则通过复杂的人物关系引发读者对多样性的思考。此外，还有《性别是条毛毛虫》一书的试读，主要反映了性别的构建及个人在性别认同方面的挣扎，并对传统二元性别划分提出质疑。
    其他文件如关于中国同性恋研究的摘录，分析了同性恋题材在中国文化中的发展，探讨了同性恋者所面临的社会压力及法律障碍。此外，何清涟的相关书籍展示了社会与文化对性别变迁的影响，《寂寞之井》则通过细腻的心理描写展现了女同性恋者的孤独与挣扎。
