url_mappings:
  - domain: "douban.com"
    dir: "豆瓣"
  - domain: "zhihu.com"
    dir: "知乎"
  - domain: "sina.com"
    dir: "新浪"
  - domain: "sina.cn"
    dir: "新浪"
  - domain: "qq.com"
    dir: "腾讯"
  - domain: "163.com"
    dir: "网易"
  - domain: "thepaper.cn"
    dir: "澎湃"
  - domain: "sohu.com"
    dir: "搜狐"
  - domain: "ifeng.com"
    dir: "凤凰网"
  - domain: "chinanews.com"
    dir: "中国新闻网"
  - domain: "*"
    dir: "未分类"
