name: 凤凰网
description: '该目录来自凤凰网，收录了一系列与多元性别相关的内容。第一篇报道《史上最强伪娘照曝光(组图)》展示了多样的伪娘形象，并引发了对跨性别文化的关注。第二篇讨论了安迪·沃霍尔的艺术生涯，特别是他与性别和边缘文化的关联，反映了他对多元文化表现的探索。这些内容不仅关注个体经历，还讨论了社会对跨性别者文化的接受度。


  随后，文章关于泰国一名年仅9岁的小孩打激素的报道，突显了跨性别者在自我认同过程中所面临的挑战和医疗难题。接下来，关于易性癖（变换性别癖）的文章分别讨论了其定义及心理治疗方法，揭示了这一群体所面临的心理困扰和治疗支持。


  报道中也涉及了未成年变性手术的法律事件，以及第一位怀孕男性的生活经历，进一步展示了多元性别个体的生存现状与家庭生活。此外，《人妖宿缘未了的爱情故事》电影的讨论，结合了跨性别与爱情主题，展示了这一领域在影视作品中的表现。最后，文章《性别都是浮云：变性人撑起半边天》强调了性别流动性和变性人在社会中的重要性，促使人们重新思考性别认同的界限。'
curator: ''
source: ''
tags:
- 多元性别
- 跨性别文化
- 伪娘
- 安迪·沃霍尔
- 性别认同
- 易性癖
- 心理治疗
- 未成年人变性手术
- 怀孕男性
- 电影
- 性别流动性
- 社会认同
license: ''
files:
- name: culture_史上最强伪娘照曝光_组图__-_读书-_凤凰网
  filename: culture_史上最强伪娘照曝光_组图__-_读书-_凤凰网.md
  type: webpage
  format: Markdown
  size: 2654
  md5: be27e2f3541dd4d39b45e7717ac16b53
  page: culture_史上最强伪娘照曝光_组图__-_读书-_凤凰网.md
- name: culture_在地下电影和造星工厂，重新发现安迪·沃霍尔_-_读书-_凤凰网
  filename: culture_在地下电影和造星工厂，重新发现安迪·沃霍尔_-_读书-_凤凰网.md
  type: webpage
  format: Markdown
  size: 15019
  md5: fe4f65d96aa79382463cb8fcb41ce15f
  page: culture_在地下电影和造星工厂，重新发现安迪·沃霍尔_-_读书-_凤凰网.md
- name: culture_美国一对男女在同时接受变性手术后成情侣_图__-_读书
  filename: culture_美国一对男女在同时接受变性手术后成情侣_图__-_读书.md
  type: webpage
  format: Markdown
  size: 1247
  md5: e51c59c0107137fc8f57e2850bbc1664
  page: culture_美国一对男女在同时接受变性手术后成情侣_图__-_读书.md
- name: ent_泰国年龄最小人妖，仅9岁一天要打3次激素
  filename: ent_泰国年龄最小人妖，仅9岁一天要打3次激素.md
  type: webpage
  format: Markdown
  size: 3264
  md5: 9d69543e5a53640d5f6e626b7a081826
  page: ent_泰国年龄最小人妖，仅9岁一天要打3次激素.md
- name: h5_异装癖：男子喜欢穿女装是什么心理
  filename: h5_异装癖：男子喜欢穿女装是什么心理.md
  type: webpage
  format: Markdown
  size: 7582
  md5: f53a1a6e1c6f4f44c45301f661fd0163
  page: h5_异装癖：男子喜欢穿女装是什么心理.md
- name: health_你知道什么是“易性癖”吗_图__健康频道
  filename: health_你知道什么是“易性癖”吗_图__健康频道.md
  type: webpage
  format: Markdown
  size: 5215
  md5: 5913c2152030579b0a0d78752fc9ff1c
  page: health_你知道什么是“易性癖”吗_图__健康频道.md
- name: health_你知道什么是“易性癖”吗_图__健康频道_-_凤凰网
  filename: health_你知道什么是“易性癖”吗_图__健康频道_-_凤凰网.md
  type: webpage
  format: Markdown
  size: 4264
  md5: 5b67527e217e575ae680603cac9a5b91
  page: health_你知道什么是“易性癖”吗_图__健康频道_-_凤凰网.md
- name: inews_21岁小伙花43万元整容变性最后惊觉自己喜欢女人_-_凤凰网
  filename: inews_21岁小伙花43万元整容变性最后惊觉自己喜欢女人_-_凤凰网.md
  type: webpage
  format: Markdown
  size: 856
  md5: dcbf29c79cfabb3e393b0aad2bb4403f
  page: inews_21岁小伙花43万元整容变性最后惊觉自己喜欢女人_-_凤凰网.md
- name: inews_您了解LES群体里性别角色的划分吗？
  filename: inews_您了解LES群体里性别角色的划分吗？.md
  type: webpage
  format: Markdown
  size: 9322
  md5: 56db8f40e4b92dd79571cc0ff65c4627
  page: inews_您了解LES群体里性别角色的划分吗？.md
- name: inews_穿裙子的男孩：异装的快乐是成为自己而非穿女装_-_凤凰网
  filename: inews_穿裙子的男孩：异装的快乐是成为自己而非穿女装_-_凤凰网.md
  type: webpage
  format: Markdown
  size: 15076
  md5: 5e3ef3b83ad0789f30cf1903c075b656
  page: inews_穿裙子的男孩：异装的快乐是成为自己而非穿女装_-_凤凰网.md
- name: mil_台湾省变性艺人利菁的爱情故事，老公是比自己小14岁的帅哥
  filename: mil_台湾省变性艺人利菁的爱情故事，老公是比自己小14岁的帅哥.md
  type: webpage
  format: Markdown
  size: 1569
  md5: dc8a44ba75934e5e2ba0108c79f550b2
  page: mil_台湾省变性艺人利菁的爱情故事，老公是比自己小14岁的帅哥.md
- name: news_17岁少女欲做变性手术家长疑其有女友_图_
  filename: news_17岁少女欲做变性手术家长疑其有女友_图_.md
  type: webpage
  format: Markdown
  size: 2706
  md5: 4bed5ee54257d24d709925e7702a5bd2
  page: news_17岁少女欲做变性手术家长疑其有女友_图_.md
- name: news_2000名跨性别者被迫绝育荷兰政府道歉并赔偿每人3.9万元_-_凤凰网
  filename: news_2000名跨性别者被迫绝育荷兰政府道歉并赔偿每人3.9万元_-_凤凰网.md
  type: webpage
  format: Markdown
  size: 2882
  md5: add3fef3901c65e2f34366b1db39ddcc
  page: news_2000名跨性别者被迫绝育荷兰政府道歉并赔偿每人3.9万元_-_凤凰网.md
- name: news_42岁“最美变性人”河莉秀与丈夫离婚_资讯频道
  filename: news_42岁“最美变性人”河莉秀与丈夫离婚_资讯频道.md
  type: webpage
  format: Markdown
  size: 895
  md5: ee54f737a168a07ff6da5683424de584
  page: news_42岁“最美变性人”河莉秀与丈夫离婚_资讯频道.md
- name: news_“我们想要一张真正的结婚证”_评论_-_凤凰网
  filename: news_“我们想要一张真正的结婚证”_评论_-_凤凰网.md
  type: webpage
  format: Markdown
  size: 3133
  md5: f53775505aa75ab916b5926ecb758874
  page: news_“我们想要一张真正的结婚证”_评论_-_凤凰网.md
- name: news_万斯暗示，中上层阶级白人孩子可能会为了进名校而成为跨性别者
  filename: news_万斯暗示，中上层阶级白人孩子可能会为了进名校而成为跨性别者.md
  type: webpage
  format: Markdown
  size: 2840
  md5: 0835c9b95bfe123307e05f15e8c1f318
  page: news_万斯暗示，中上层阶级白人孩子可能会为了进名校而成为跨性别者.md
- name: news_中国刑法学“被变性”引争议司法部展开调查
  filename: news_中国刑法学“被变性”引争议司法部展开调查.md
  type: webpage
  format: Markdown
  size: 5569
  md5: 1d0444234c623c59c2e13097c5384b92
  page: news_中国刑法学“被变性”引争议司法部展开调查.md
- name: news_为什么大家突然不爱看电影了？_-_凤凰网
  filename: news_为什么大家突然不爱看电影了？_-_凤凰网.md
  type: webpage
  format: Markdown
  size: 27141
  md5: 3a3674b1dafade1dc68be8995bca7bc5
  page: news_为什么大家突然不爱看电影了？_-_凤凰网.md
- name: news_俄罗斯规定变性人和跨性人不得领驾照称为了减少车祸
  filename: news_俄罗斯规定变性人和跨性人不得领驾照称为了减少车祸.md
  type: webpage
  format: Markdown
  size: 1757
  md5: 785a562432d55f58e174afc9534d1f95
  page: news_俄罗斯规定变性人和跨性人不得领驾照称为了减少车祸.md
- name: news_全国首例男大学生完成丰胸手术公开变性_组图_
  filename: news_全国首例男大学生完成丰胸手术公开变性_组图_.md
  type: webpage
  format: Markdown
  size: 1848
  md5: 785797c4741ca1680a690e34cb80727e
  page: news_全国首例男大学生完成丰胸手术公开变性_组图_.md
- name: news_变性手术多年后，一位终身共和党人决定投票给哈里斯
  filename: news_变性手术多年后，一位终身共和党人决定投票给哈里斯.md
  type: webpage
  format: Markdown
  size: 4344
  md5: 35507d1efaf87489ad4678b2ac182178
  page: news_变性手术多年后，一位终身共和党人决定投票给哈里斯.md
- name: news_变性男子获环球小姐最上镜奖父母怒砸美容院图
  filename: news_变性男子获环球小姐最上镜奖父母怒砸美容院图.md
  type: webpage
  format: Markdown
  size: 7265
  md5: aa422a16ba181338ffbf1ee4c3aed005
  page: news_变性男子获环球小姐最上镜奖父母怒砸美容院图.md
- name: news_变性舞蹈家金星与外籍前夫同现身恩爱依旧
  filename: news_变性舞蹈家金星与外籍前夫同现身恩爱依旧.md
  type: webpage
  format: Markdown
  size: 1175
  md5: 331b5e49ad405e88afc3dca2b996f7b2
  page: news_变性舞蹈家金星与外籍前夫同现身恩爱依旧.md
- name: news_台湾短跑名将曾是双性人变性成为女人退出体坛
  filename: news_台湾短跑名将曾是双性人变性成为女人退出体坛.md
  type: webpage
  format: Markdown
  size: 2060
  md5: 2255295312c2cc0cc40d776b6782d3ed
  page: news_台湾短跑名将曾是双性人变性成为女人退出体坛.md
- name: news_台男子因变性手术致肢体残障医院被判赔173万
  filename: news_台男子因变性手术致肢体残障医院被判赔173万.md
  type: webpage
  format: Markdown
  size: 2440
  md5: 3b2b487e8f943b96b80c1f0b8108791a
  page: news_台男子因变性手术致肢体残障医院被判赔173万.md
- name: news_回击第一夫人变性谣言，马克龙出面护妻
  filename: news_回击第一夫人变性谣言，马克龙出面护妻.md
  type: webpage
  format: Markdown
  size: 2758
  md5: ae447fae53945b8d95384e1ca1dff943
  page: news_回击第一夫人变性谣言，马克龙出面护妻.md
- name: news_大胡子“美女歌神”变身照曝光变性前是奶油小生_高清组图_
  filename: news_大胡子“美女歌神”变身照曝光变性前是奶油小生_高清组图_.md
  type: webpage
  format: Markdown
  size: 1244
  md5: ece21f08669e4a35f8e8e8a13e421dc6
  page: news_大胡子“美女歌神”变身照曝光变性前是奶油小生_高清组图_.md
- name: news_女子支持父亲与丈夫一起变性三人成闺密_图_
  filename: news_女子支持父亲与丈夫一起变性三人成闺密_图_.md
  type: webpage
  format: Markdown
  size: 2881
  md5: 00d7eeee40c543e78c764d6831499a2b
  page: news_女子支持父亲与丈夫一起变性三人成闺密_图_.md
- name: news_德国男议员任职期间变性成女子
  filename: news_德国男议员任职期间变性成女子.md
  type: webpage
  format: Markdown
  size: 505
  md5: 97e5a815227ab36da36f82a65a8d759b
  page: news_德国男议员任职期间变性成女子.md
- name: news_成都：实习医生为15岁少年摘除睾丸变性被批捕
  filename: news_成都：实习医生为15岁少年摘除睾丸变性被批捕.md
  type: webpage
  format: Markdown
  size: 3808
  md5: 43d515a329a40d7c0f046348a5544938
  page: news_成都：实习医生为15岁少年摘除睾丸变性被批捕.md
- name: news_我要变性”_引诧异目光（图）_资讯-_两小伙昆明街头挂牌
  filename: news_我要变性”_引诧异目光（图）_资讯-_两小伙昆明街头挂牌.md
  type: webpage
  format: Markdown
  size: 4680
  md5: bcecb910d93db6c958687159a52d3a82
  page: news_我要变性”_引诧异目光（图）_资讯-_两小伙昆明街头挂牌.md
- name: news_新西兰一举重选手成为首位参加奥运会的变性运动员
  filename: news_新西兰一举重选手成为首位参加奥运会的变性运动员.md
  type: webpage
  format: Markdown
  size: 1511
  md5: def5d8eb6226936f672a27285ec49b4a
  page: news_新西兰一举重选手成为首位参加奥运会的变性运动员.md
- name: news_日本变性人选美皇后凯旋后推出首部写真集
  filename: news_日本变性人选美皇后凯旋后推出首部写真集.md
  type: webpage
  format: Markdown
  size: 1569
  md5: 4dbede905e771a9437941e07b50e604f
  page: news_日本变性人选美皇后凯旋后推出首部写真集.md
- name: news_泰国人妖选美20岁佳丽娜蒂“艳冠群芳”_组图__-_凤凰网
  filename: news_泰国人妖选美20岁佳丽娜蒂“艳冠群芳”_组图__-_凤凰网.md
  type: webpage
  format: Markdown
  size: 1731
  md5: bf7a496d7d835297966819f4a10c7eb8
  page: news_泰国人妖选美20岁佳丽娜蒂“艳冠群芳”_组图__-_凤凰网.md
- name: news_泰国变性人选美大赛现场
  filename: news_泰国变性人选美大赛现场.md
  type: webpage
  format: Markdown
  size: 618
  md5: 05f8a4c8ce9cf293287acd664fcc71c9
  page: news_泰国变性人选美大赛现场.md
- name: news_男子想变性花钱让人割睾丸“主刀网友”涉非法行医
  filename: news_男子想变性花钱让人割睾丸“主刀网友”涉非法行医.md
  type: webpage
  format: Markdown
  size: 4819
  md5: a84aa311c616f4c312c51c06f27a6dbe
  page: news_男子想变性花钱让人割睾丸“主刀网友”涉非法行医.md
- name: news_男子相亲遇变性人恼羞成怒与女子当场掐架_组图_
  filename: news_男子相亲遇变性人恼羞成怒与女子当场掐架_组图_.md
  type: webpage
  format: Markdown
  size: 2659
  md5: d7daa98eea38180746e40890dd7b2baa
  page: news_男子相亲遇变性人恼羞成怒与女子当场掐架_组图_.md
- name: news_维密迎首位变性模特高管曾因反对变性人代言被喷
  filename: news_维密迎首位变性模特高管曾因反对变性人代言被喷.md
  type: webpage
  format: Markdown
  size: 892
  md5: 55e2478b7f64f5b582ecd26a8af24310
  page: news_维密迎首位变性模特高管曾因反对变性人代言被喷.md
- name: news_美一高中200学生抗议变性人用女厕所：她还没做手术
  filename: news_美一高中200学生抗议变性人用女厕所：她还没做手术.md
  type: webpage
  format: Markdown
  size: 1903
  md5: 23cdb86fe2c3c87cbc1b0b5a3e03d549
  page: news_美一高中200学生抗议变性人用女厕所：她还没做手术.md
- name: news_美国怀孕男子更多生活照片曝光_组图_
  filename: news_美国怀孕男子更多生活照片曝光_组图_.md
  type: webpage
  format: Markdown
  size: 1624
  md5: 59f8cb7b381e9fb9c3295897c4cc8417
  page: news_美国怀孕男子更多生活照片曝光_组图_.md
- name: news_美国监狱拒绝为杀妻囚犯提供变性治疗被诉
  filename: news_美国监狱拒绝为杀妻囚犯提供变性治疗被诉.md
  type: webpage
  format: Markdown
  size: 3795
  md5: d4951d7ab9c613677f97dc71090c16b0
  page: news_美国监狱拒绝为杀妻囚犯提供变性治疗被诉.md
- name: news_英一杀手狱中变性成老太与女杀手相恋结婚_图_
  filename: news_英一杀手狱中变性成老太与女杀手相恋结婚_图_.md
  type: webpage
  format: Markdown
  size: 4716
  md5: 1f241e10dcb05611e63f07d6ec3c2e1e
  page: news_英一杀手狱中变性成老太与女杀手相恋结婚_图_.md
- name: news_英国27岁帅哥军官变性成美女
  filename: news_英国27岁帅哥军官变性成美女.md
  type: webpage
  format: Markdown
  size: 1400
  md5: 81cead13c9bf7b267dd8c726a099b1df
  page: news_英国27岁帅哥军官变性成美女.md
- name: news_英国两男子相恋双双变性后步入婚姻殿堂（组图）
  filename: news_英国两男子相恋双双变性后步入婚姻殿堂（组图）.md
  type: webpage
  format: Markdown
  size: 1022
  md5: 797f2c33661b95fa036c56dc6dda014c
  page: news_英国两男子相恋双双变性后步入婚姻殿堂（组图）.md
- name: news_英国为性别认同障碍儿童提供药物辅助变性手术
  filename: news_英国为性别认同障碍儿童提供药物辅助变性手术.md
  type: webpage
  format: Markdown
  size: 2570
  md5: b4a3cb8d8d2012c6368856d5dd20ad2b
  page: news_英国为性别认同障碍儿童提供药物辅助变性手术.md
- name: news_英国男子在泰国与变性人发生冲突被打倒_资讯频道
  filename: news_英国男子在泰国与变性人发生冲突被打倒_资讯频道.md
  type: webpage
  format: Markdown
  size: 1782
  md5: f1224f9547a8e6913413f92767362307
  page: news_英国男子在泰国与变性人发生冲突被打倒_资讯频道.md
- name: news_越南变性人裸体站警车旁引围观警方称其只是在秀身材
  filename: news_越南变性人裸体站警车旁引围观警方称其只是在秀身材.md
  type: webpage
  format: Markdown
  size: 1222
  md5: 34954701746292ef267229aa810cb21c
  page: news_越南变性人裸体站警车旁引围观警方称其只是在秀身材.md
- name: news_金星首次和母亲提变性时，母亲十分坦然的就接受了
  filename: news_金星首次和母亲提变性时，母亲十分坦然的就接受了.md
  type: webpage
  format: Markdown
  size: 858
  md5: a890abdc43a6264153a264aa6491b112
  page: news_金星首次和母亲提变性时，母亲十分坦然的就接受了.md
- name: news_阿根廷变性人因在臀部注射工业硅胶死亡_图_
  filename: news_阿根廷变性人因在臀部注射工业硅胶死亡_图_.md
  type: webpage
  format: Markdown
  size: 1639
  md5: e9bfaacd040c353563ce86d3961685fb
  page: news_阿根廷变性人因在臀部注射工业硅胶死亡_图_.md
- name: news_韩国28岁男子强奸变性人被判刑3年
  filename: news_韩国28岁男子强奸变性人被判刑3年.md
  type: webpage
  format: Markdown
  size: 1664
  md5: ab41a0f31719e26176a2deb2afe3dd17
  page: news_韩国28岁男子强奸变性人被判刑3年.md
- name: phtv_1978-2006_中国性解冻纪实（组图）_-_凤凰卫视
  filename: phtv_1978-2006_中国性解冻纪实（组图）_-_凤凰卫视.md
  type: webpage
  format: Markdown
  size: 1313
  md5: a168ada342e1592255c149312b53cf05
  page: phtv_1978-2006_中国性解冻纪实（组图）_-_凤凰卫视.md
- name: phtv_透过美艳的人妖品位泰国（组图）_-_凤凰卫视
  filename: phtv_透过美艳的人妖品位泰国（组图）_-_凤凰卫视.md
  type: webpage
  format: Markdown
  size: 2924
  md5: 5839d9bc7c409b8e4e06d7324a1d68f6
  page: phtv_透过美艳的人妖品位泰国（组图）_-_凤凰卫视.md
- name: phtv_金星：变性手术使我面临终身残废被至亲陷害遭拘留_-_凤凰卫视
  filename: phtv_金星：变性手术使我面临终身残废被至亲陷害遭拘留_-_凤凰卫视.md
  type: webpage
  format: Markdown
  size: 2978
  md5: 207731951ff9ffabffcfd5abe988d5fa
  page: phtv_金星：变性手术使我面临终身残废被至亲陷害遭拘留_-_凤凰卫视.md
- name: pit_经典奇幻喜剧冒险电影人妖宿缘未了的爱情故事结局美好吗
  filename: pit_经典奇幻喜剧冒险电影人妖宿缘未了的爱情故事结局美好吗.md
  type: webpage
  format: Markdown
  size: 3501
  md5: 9842bbdd0dc98f48ec0b3ddb39c44cde
  page: pit_经典奇幻喜剧冒险电影人妖宿缘未了的爱情故事结局美好吗.md
- name: pit_经典奇幻喜剧冒险电影人妖宿缘未了的爱情故事结局美好吗_1
  filename: pit_经典奇幻喜剧冒险电影人妖宿缘未了的爱情故事结局美好吗_1.md
  type: webpage
  format: Markdown
  size: 6439
  md5: ae36354e8866e0a7113b607c501366d0
  page: pit_经典奇幻喜剧冒险电影人妖宿缘未了的爱情故事结局美好吗_1.md
- name: sports_盘点体坛变性人奥运史上少女脱光力证清白_图__-_体育
  filename: sports_盘点体坛变性人奥运史上少女脱光力证清白_图__-_体育.md
  type: webpage
  format: Markdown
  size: 4293
  md5: 6a7733b477ca8b84dd65279d24b8e034
  page: sports_盘点体坛变性人奥运史上少女脱光力证清白_图__-_体育.md
- name: yue_性别都是浮云变性人撑起半边天_-_音乐-_凤凰网
  filename: yue_性别都是浮云变性人撑起半边天_-_音乐-_凤凰网.md
  type: webpage
  format: Markdown
  size: 2690
  md5: 95772c77260010e901d6e0b9e6bb2771
  page: yue_性别都是浮云变性人撑起半边天_-_音乐-_凤凰网.md
- name: yue_英国爆出首例“男妈妈”：30岁变性者产下一子_图__-_音乐-_凤凰网
  filename: yue_英国爆出首例“男妈妈”：30岁变性者产下一子_图__-_音乐-_凤凰网.md
  type: webpage
  format: Markdown
  size: 2125
  md5: bf6a269bed02c43f7f802ffa1c0577dd
  page: yue_英国爆出首例“男妈妈”：30岁变性者产下一子_图__-_音乐-_凤凰网.md
subdirs: []
