name: 凤凰网
description: '该目录来自凤凰网，收录了一系列与多元性别相关的内容。第一篇报道《史上最强伪娘照曝光(组图)》展示了多样的伪娘形象，并引发了对跨性别文化的关注。第二篇讨论了安迪·沃霍尔的艺术生涯，特别是他与性别和边缘文化的关联，反映了他对多元文化表现的探索。这些内容不仅关注个体经历，还讨论了社会对跨性别者文化的接受度。


  随后，文章关于泰国一名年仅9岁的小孩打激素的报道，突显了跨性别者在自我认同过程中所面临的挑战和医疗难题。接下来，关于易性癖（变换性别癖）的文章分别讨论了其定义及心理治疗方法，揭示了这一群体所面临的心理困扰和治疗支持。


  报道中也涉及了未成年变性手术的法律事件，以及第一位怀孕男性的生活经历，进一步展示了多元性别个体的生存现状与家庭生活。此外，《人妖宿缘未了的爱情故事》电影的讨论，结合了跨性别与爱情主题，展示了这一领域在影视作品中的表现。最后，文章《性别都是浮云：变性人撑起半边天》强调了性别流动性和变性人在社会中的重要性，促使人们重新思考性别认同的界限。'
curator: ''
source: ''
tags:
- 多元性别
- 跨性别文化
- 伪娘
- 安迪·沃霍尔
- 性别认同
- 易性癖
- 心理治疗
- 未成年人变性手术
- 怀孕男性
- 电影
- 性别流动性
- 社会认同
license: ''
files:
- name: culture_史上最强伪娘照曝光_组图__-_读书-_凤凰网
  filename: culture_史上最强伪娘照曝光_组图__-_读书-_凤凰网.md
  type: webpage
  format: Markdown
  size: 2654
  md5: be27e2f3541dd4d39b45e7717ac16b53
  page: culture_史上最强伪娘照曝光_组图__-_读书-_凤凰网.md
- name: culture_在地下电影和造星工厂，重新发现安迪·沃霍尔_-_读书-_凤凰网
  filename: culture_在地下电影和造星工厂，重新发现安迪·沃霍尔_-_读书-_凤凰网.md
  type: webpage
  format: Markdown
  size: 15019
  md5: fe4f65d96aa79382463cb8fcb41ce15f
  page: culture_在地下电影和造星工厂，重新发现安迪·沃霍尔_-_读书-_凤凰网.md
- name: ent_泰国年龄最小人妖，仅9岁一天要打3次激素
  filename: ent_泰国年龄最小人妖，仅9岁一天要打3次激素.md
  type: webpage
  format: Markdown
  size: 3264
  md5: 9d69543e5a53640d5f6e626b7a081826
  page: ent_泰国年龄最小人妖，仅9岁一天要打3次激素.md
- name: health_你知道什么是“易性癖”吗_图__健康频道
  filename: health_你知道什么是“易性癖”吗_图__健康频道.md
  type: webpage
  format: Markdown
  size: 5215
  md5: 5913c2152030579b0a0d78752fc9ff1c
  page: health_你知道什么是“易性癖”吗_图__健康频道.md
- name: health_你知道什么是“易性癖”吗_图__健康频道_-_凤凰网
  filename: health_你知道什么是“易性癖”吗_图__健康频道_-_凤凰网.md
  type: webpage
  format: Markdown
  size: 4264
  md5: 5b67527e217e575ae680603cac9a5b91
  page: health_你知道什么是“易性癖”吗_图__健康频道_-_凤凰网.md
- name: news_为什么大家突然不爱看电影了？_-_凤凰网
  filename: news_为什么大家突然不爱看电影了？_-_凤凰网.md
  type: webpage
  format: Markdown
  size: 27141
  md5: 3a3674b1dafade1dc68be8995bca7bc5
  page: news_为什么大家突然不爱看电影了？_-_凤凰网.md
- name: news_成都：实习医生为15岁少年摘除睾丸变性被批捕
  filename: news_成都：实习医生为15岁少年摘除睾丸变性被批捕.md
  type: webpage
  format: Markdown
  size: 3808
  md5: 43d515a329a40d7c0f046348a5544938
  page: news_成都：实习医生为15岁少年摘除睾丸变性被批捕.md
- name: news_美国怀孕男子更多生活照片曝光_组图_
  filename: news_美国怀孕男子更多生活照片曝光_组图_.md
  type: webpage
  format: Markdown
  size: 1624
  md5: 59f8cb7b381e9fb9c3295897c4cc8417
  page: news_美国怀孕男子更多生活照片曝光_组图_.md
- name: pit_经典奇幻喜剧冒险电影人妖宿缘未了的爱情故事结局美好吗
  filename: pit_经典奇幻喜剧冒险电影人妖宿缘未了的爱情故事结局美好吗.md
  type: webpage
  format: Markdown
  size: 3501
  md5: 9842bbdd0dc98f48ec0b3ddb39c44cde
  page: pit_经典奇幻喜剧冒险电影人妖宿缘未了的爱情故事结局美好吗.md
- name: yue_性别都是浮云变性人撑起半边天_-_音乐-_凤凰网
  filename: yue_性别都是浮云变性人撑起半边天_-_音乐-_凤凰网.md
  type: webpage
  format: Markdown
  size: 2690
  md5: 95772c77260010e901d6e0b9e6bb2771
  page: yue_性别都是浮云变性人撑起半边天_-_音乐-_凤凰网.md
subdirs: []
