name: 网易
description: 该目录收录了与多元性别相关的各类内容，涵盖了变性人的生命故事、网络文化现象以及社会新闻报道。首先，包含了一位名为黄宁倩的变性人自述经历，详细描述了她心路历程和在传统婚姻中面临的挣扎。这些故事反映了社会对变性人及其性别认同进程的态度，尤其是家庭的影响。同时，对“女装大佬”这一网络现象进行了讨论，展示了跨性别表达在二次元文化中的表现，并探讨了文化背景下性别表现的多样性。此外，关于变性手术的网友评论展示了个人的过渡经历，强调了跨性别者在日常生活中遇到的挑战与成功。该目录还涵盖了一些与游戏文化相关的讨论，如游戏角色的性别表现及其在社交平台上的接受度，进一步展现了互联网时代性别认同的复杂性。
curator: ''
source: ''
tags:
- 变性人
- 跨性别故事
- 女装大佬
- 网络文化
- 性别认同
- 个人经历
- 游戏文化
- 社会新闻
- 二次元文化
- 性别表现
license: ''
files:
- name: c_2004年安徽一男子做手术变性，而后高调征婚，邂逅真爱生活如何？
  filename: c_2004年安徽一男子做手术变性，而后高调征婚，邂逅真爱生活如何？.md
  type: webpage
  format: Markdown
  size: 22855
  md5: 961a6f959dcb444cdedf4b30a4e6ce37
  page: c_2004年安徽一男子做手术变性，而后高调征婚，邂逅真爱生活如何？.md
- name: c_你讨厌女装大佬吗？你觉得他的存在合理吗？_-_网易新闻
  filename: c_你讨厌女装大佬吗？你觉得他的存在合理吗？_-_网易新闻.md
  type: webpage
  format: Markdown
  size: 4188
  md5: 18205cde03afae2fcc2a8ef34f220a92
  page: c_你讨厌女装大佬吗？你觉得他的存在合理吗？_-_网易新闻.md
- name: comment_美国多所学校禁止学生穿洞洞鞋_网易跟贴
  filename: comment_美国多所学校禁止学生穿洞洞鞋_网易跟贴.md
  type: webpage
  format: Markdown
  size: 1559
  md5: a60b45cdf3cfda0f075616ce39be2540
  page: comment_美国多所学校禁止学生穿洞洞鞋_网易跟贴.md
- name: comment_话题：成功的做了一场变性手术_-_网易
  filename: comment_话题：成功的做了一场变性手术_-_网易.md
  type: webpage
  format: Markdown
  size: 3109
  md5: e64a1f995482999a191b4226852a0907
  page: comment_话题：成功的做了一场变性手术_-_网易.md
- name: dh2_龙叔竟变身“女装大佬”？画面太美我不敢看！_-_大话西游2免费版_-_网易
  filename: dh2_龙叔竟变身“女装大佬”？画面太美我不敢看！_-_大话西游2免费版_-_网易.md
  type: webpage
  format: Markdown
  size: 6956
  md5: 29a920115fdbf94d3ad62262ec12ff95
  page: dh2_龙叔竟变身“女装大佬”？画面太美我不敢看！_-_大话西游2免费版_-_网易.md
- name: ds_大神男娘
  filename: ds_大神男娘.md
  type: webpage
  format: Markdown
  size: 7362
  md5: 002c29aa65209ded811d9c38eec7d1be
  page: ds_大神男娘.md
- name: ds_新衣服配我的女装大佬脸竟然…比想象中好一点_明日之后_大神
  filename: ds_新衣服配我的女装大佬脸竟然…比想象中好一点_明日之后_大神.md
  type: webpage
  format: Markdown
  size: 4741
  md5: 8411d4044ff93dd47e298f1c5beb1417
  page: ds_新衣服配我的女装大佬脸竟然…比想象中好一点_明日之后_大神.md
- name: ds_明日之后,寻找明日女神明日女神合集女装大佬篇：人家这么可爱_明日_
  filename: ds_明日之后,寻找明日女神明日女神合集女装大佬篇：人家这么可爱_明日_.md
  type: webpage
  format: Markdown
  size: 14044
  md5: 497d3101e260a624a833589a2389a486
  page: ds_明日之后,寻找明日女神明日女神合集女装大佬篇：人家这么可爱_明日_.md
- name: ent_变性人_标签_-_网易娱乐
  filename: ent_变性人_标签_-_网易娱乐.md
  type: webpage
  format: Markdown
  size: 20411
  md5: a3ad6dd99155e8e256c1b009ea2d70dc
  page: ent_变性人_标签_-_网易娱乐.md
- name: kids_15岁女孩要变性做男人
  filename: kids_15岁女孩要变性做男人.md
  type: webpage
  format: Markdown
  size: 2312
  md5: e383ef907345d6e71428e61fbeb2c63b
  page: kids_15岁女孩要变性做男人.md
- name: kids_15岁女孩要变性做男人_-_网易教育
  filename: kids_15岁女孩要变性做男人_-_网易教育.md
  type: webpage
  format: Markdown
  size: 2120
  md5: be93f6b2b2ee8f4565ccc5b12b7734c3
  page: kids_15岁女孩要变性做男人_-_网易教育.md
- name: m_泰国人妖韩国娘炮日本废宅，为啥有美国驻军的国家，都快速娘化？
  filename: m_泰国人妖韩国娘炮日本废宅，为啥有美国驻军的国家，都快速娘化？.md
  type: webpage
  format: Markdown
  size: 6290
  md5: ce57f0456220c0888b4b4a67dd7e55b7
  page: m_泰国人妖韩国娘炮日本废宅，为啥有美国驻军的国家，都快速娘化？.md
- name: m_网曝易建联出轨！女方身份被扒：疑似在新加坡留学、是跨性别者
  filename: m_网曝易建联出轨！女方身份被扒：疑似在新加坡留学、是跨性别者.md
  type: webpage
  format: Markdown
  size: 9318
  md5: 1c6fe2ecf65cfeb4310662b828e40b75
  page: m_网曝易建联出轨！女方身份被扒：疑似在新加坡留学、是跨性别者.md
- name: m_这部动画的男主角最爱穿女装，第一次约会把妹子吓得够呛_-_网易
  filename: m_这部动画的男主角最爱穿女装，第一次约会把妹子吓得够呛_-_网易.md
  type: webpage
  format: Markdown
  size: 7195
  md5: bb07bc4ae4323aa72b041740e1c46080
  page: m_这部动画的男主角最爱穿女装，第一次约会把妹子吓得够呛_-_网易.md
- name: money_异装癖-_标签_网易出品
  filename: money_异装癖-_标签_网易出品.md
  type: webpage
  format: Markdown
  size: 9383
  md5: 969f7133c0d1983495215a1f4ce184a6
  page: money_异装癖-_标签_网易出品.md
- name: money_桃色-_标签_网易出品
  filename: money_桃色-_标签_网易出品.md
  type: webpage
  format: Markdown
  size: 8190
  md5: fa7f9cb7dd3b4e4ac2c15b90af45faa4
  page: money_桃色-_标签_网易出品.md
- name: music_「人妖」李二毛的一生_-_网易云音乐
  filename: music_「人妖」李二毛的一生_-_网易云音乐.md
  type: webpage
  format: Markdown
  size: 3083
  md5: df77d4e18f7ac90aec292c40b2b079be
  page: music_「人妖」李二毛的一生_-_网易云音乐.md
- name: music_ひまわりの約束高清版-_秦基博-_高清MV_-_网易云音乐
  filename: music_ひまわりの約束高清版-_秦基博-_高清MV_-_网易云音乐.md
  type: webpage
  format: Markdown
  size: 3169
  md5: 2889343766f96793bfcbdeef9118bf76
  page: music_ひまわりの約束高清版-_秦基博-_高清MV_-_网易云音乐.md
- name: music_谁说J家不出女团？！向女装大佬们低头！！_-_视频-_网易云音乐
  filename: music_谁说J家不出女团？！向女装大佬们低头！！_-_视频-_网易云音乐.md
  type: webpage
  format: Markdown
  size: 241
  md5: caac6fd2fbc3ca95546d4cdae944c5c0
  page: music_谁说J家不出女团？！向女装大佬们低头！！_-_视频-_网易云音乐.md
- name: news_在爱情夹缝里的人社会新闻周刊
  filename: news_在爱情夹缝里的人社会新闻周刊.md
  type: webpage
  format: Markdown
  size: 11734
  md5: ee650b2ce5ebf006479eb43045a77430
  page: news_在爱情夹缝里的人社会新闻周刊.md
- name: news_泰国_标签_网易出品
  filename: news_泰国_标签_网易出品.md
  type: webpage
  format: Markdown
  size: 6319
  md5: abb332353f649ce36f9356708a64dc8a
  page: news_泰国_标签_网易出品.md
- name: open_昔日发小整容变性，摇身一变成了女朋友，这部韩国悬疑片绝了
  filename: open_昔日发小整容变性，摇身一变成了女朋友，这部韩国悬疑片绝了.md
  type: webpage
  format: Markdown
  size: 1644
  md5: b767ae9bf5a95ce76dfa504c9b45cf43
  page: open_昔日发小整容变性，摇身一变成了女朋友，这部韩国悬疑片绝了.md
- name: qwq_雷蕾驾到！《非人学园》雷震子性转时装曝光_-_网易
  filename: qwq_雷蕾驾到！《非人学园》雷震子性转时装曝光_-_网易.md
  type: webpage
  format: Markdown
  size: 6372
  md5: d20d3e9eeb9850adb66d80fc6c56ce93
  page: qwq_雷蕾驾到！《非人学园》雷震子性转时装曝光_-_网易.md
- name: tech_双性人_标签_网易出品
  filename: tech_双性人_标签_网易出品.md
  type: webpage
  format: Markdown
  size: 20022
  md5: bf86a0658e81beb13e0a1bf97ba264be
  page: tech_双性人_标签_网易出品.md
- name: tech_科普要闻_科学频道
  filename: tech_科普要闻_科学频道.md
  type: webpage
  format: Markdown
  size: 7613
  md5: 29fb9e97de8763ba2175005df1507015
  page: tech_科普要闻_科学频道.md
- name: tech_跨性别-_标签_网易出品
  filename: tech_跨性别-_标签_网易出品.md
  type: webpage
  format: Markdown
  size: 6821
  md5: 2464afc70ccfd0e460876df7b2ddd651
  page: tech_跨性别-_标签_网易出品.md
- name: travel_变性人_标签_-_网易旅游
  filename: travel_变性人_标签_-_网易旅游.md
  type: webpage
  format: Markdown
  size: 7776
  md5: 6c4d0f79f109190dde462883a05af686
  page: travel_变性人_标签_-_网易旅游.md
- name: www_11月3日，河南，郑州大学生夜骑自行车去开封，开封城管心疼娃们太_
  filename: www_11月3日，河南，郑州大学生夜骑自行车去开封，开封城管心疼娃们太_.md
  type: webpage
  format: Markdown
  size: 4191
  md5: b379743ec67e1f85aae758f2a4a004bc
  page: www_11月3日，河南，郑州大学生夜骑自行车去开封，开封城管心疼娃们太_.md
- name: www_8年前，那个娶了泰国“人妖皇后”的北京男子，现在后悔了吗？_-_网易
  filename: www_8年前，那个娶了泰国“人妖皇后”的北京男子，现在后悔了吗？_-_网易.md
  type: webpage
  format: Markdown
  size: 4135
  md5: cba98f00ed503ae1c11775b6040a8fa9
  page: www_8年前，那个娶了泰国“人妖皇后”的北京男子，现在后悔了吗？_-_网易.md
- name: www_成功的做了一场变性手术_-_网易
  filename: www_成功的做了一场变性手术_-_网易.md
  type: webpage
  format: Markdown
  size: 5607
  md5: 5f5485e9226f2adfc3cce4ff48f3c75a
  page: www_成功的做了一场变性手术_-_网易.md
- name: www_我，26岁，性焦虑了。_-_网易
  filename: www_我，26岁，性焦虑了。_-_网易.md
  type: webpage
  format: Markdown
  size: 9075
  md5: 1e268a8a6bbef66ff0e99817ac92fd51
  page: www_我，26岁，性焦虑了。_-_网易.md
- name: www_泰国最美的人妖皇后，被中国土豪娶走，婚后生活怎样呢？_-_网易
  filename: www_泰国最美的人妖皇后，被中国土豪娶走，婚后生活怎样呢？_-_网易.md
  type: webpage
  format: Markdown
  size: 4228
  md5: 3bec069b1c1c31249acbff6d57bd8af5
  page: www_泰国最美的人妖皇后，被中国土豪娶走，婚后生活怎样呢？_-_网易.md
- name: www_特朗普胜选后，马斯克跨性别女儿宣称要离开美国_-_网易
  filename: www_特朗普胜选后，马斯克跨性别女儿宣称要离开美国_-_网易.md
  type: webpage
  format: Markdown
  size: 6731
  md5: ae6d67805d54457f4e4e6b678474f66a
  page: www_特朗普胜选后，马斯克跨性别女儿宣称要离开美国_-_网易.md
- name: www_男扮女装伪装成公主的我，将敌国摄政王给睡了古代小说_-_网易
  filename: www_男扮女装伪装成公主的我，将敌国摄政王给睡了古代小说_-_网易.md
  type: webpage
  format: Markdown
  size: 12509
  md5: 7cba34f49ad754daa2c6649c0892b7ef
  page: www_男扮女装伪装成公主的我，将敌国摄政王给睡了古代小说_-_网易.md
- name: www_这么可爱一定是男孩子！刷了这么多年的梗，你真的了解伪娘吗？_-_网易
  filename: www_这么可爱一定是男孩子！刷了这么多年的梗，你真的了解伪娘吗？_-_网易.md
  type: webpage
  format: Markdown
  size: 8000
  md5: 56ed3487a8514d1c80ae933aa0a34b1f
  page: www_这么可爱一定是男孩子！刷了这么多年的梗，你真的了解伪娘吗？_-_网易.md
- name: www_金星两天连发两条微博，直言爱自己，做自己，与性别无关!_-_网易
  filename: www_金星两天连发两条微博，直言爱自己，做自己，与性别无关!_-_网易.md
  type: webpage
  format: Markdown
  size: 3260
  md5: 73ad4d568fadec9858e54063de7508e4
  page: www_金星两天连发两条微博，直言爱自己，做自己，与性别无关!_-_网易.md
- name: www_金星真不冤！继广州后金星又被拒绝，佛山大剧院：太多人举报她！
  filename: www_金星真不冤！继广州后金星又被拒绝，佛山大剧院：太多人举报她！.md
  type: webpage
  format: Markdown
  size: 2962
  md5: f10e917b2387447e1689f40389c9e7f4
  page: www_金星真不冤！继广州后金星又被拒绝，佛山大剧院：太多人举报她！.md
- name: xyq_人妖怎么了!_-_梦幻西游-_网易
  filename: xyq_人妖怎么了!_-_梦幻西游-_网易.md
  type: webpage
  format: Markdown
  size: 2453
  md5: 1f551681dd766c2e4306846d5c3be2a3
  page: xyq_人妖怎么了!_-_梦幻西游-_网易.md
- name: xyq_人妖的定义_-_梦幻西游-_网易
  filename: xyq_人妖的定义_-_梦幻西游-_网易.md
  type: webpage
  format: Markdown
  size: 2370
  md5: 17bdd670fe99494f64075791c8cd0945
  page: xyq_人妖的定义_-_梦幻西游-_网易.md
- name: xyq_爱情从人妖开始-_《梦幻西游》电脑版官方网站_-_网易
  filename: xyq_爱情从人妖开始-_《梦幻西游》电脑版官方网站_-_网易.md
  type: webpage
  format: Markdown
  size: 6916
  md5: aa5f27e27f104c9620f9ed0b16fa72ff
  page: xyq_爱情从人妖开始-_《梦幻西游》电脑版官方网站_-_网易.md
subdirs: []
