name: 新浪
description: 本目录包含来自新浪的博客内容，聚焦于多元性别文化和相关社群的表达与经历。包括了豪歌在cosplay圈的活动记录，此项活动展示了该团体在cosplay领域的影响力，共同强调了多元性别表现的艺术形式。广州的一次轻松变装聚会介绍了变装文化的社交平台，适用于多元性别参与者，表明了社会对变装文化的接纳与支持。关于异装癖和伪娘现象的文章反映了个体在性别认同上所面临的挑战与社会期待。接下来的一些故事作品，通过小说形式，描述了双性人和变性人的生存状态和心理挣扎，展现了性别认同对个体的重要性。此外，还讨论了跨性别文化与西方文化的关系，提供了对文化背景的视角和理解。
curator: ''
source: ''
tags:
- 多元性别
- cosplay
- 变装文化
- 异装癖
- 伪娘
- 双性人
- 变性人
- 小说
- 跨性别文化
- 社会认同
license: ''
files:
- name: blog_2013豪歌cosplay新作saber女仆版正片【爱丽丝伪娘团】
  filename: blog_2013豪歌cosplay新作saber女仆版正片【爱丽丝伪娘团】.md
  type: webpage
  format: Markdown
  size: 1488
  md5: 3e40ed68bf9ac985cbb3c1c74839e722
  page: blog_2013豪歌cosplay新作saber女仆版正片【爱丽丝伪娘团】.md
- name: blog_LJL最新伪街目的地，来一次轻松的变装之旅吧！！
  filename: blog_LJL最新伪街目的地，来一次轻松的变装之旅吧！！.md
  type: webpage
  format: Markdown
  size: 4992
  md5: 17c83701dde4a478175bc7714cc1664c
  page: blog_LJL最新伪街目的地，来一次轻松的变装之旅吧！！.md
- name: blog__转载_异装癖？_Xavier杰斯君_-_新浪网站导航
  filename: blog__转载_异装癖？_Xavier杰斯君_-_新浪网站导航.md
  type: webpage
  format: Markdown
  size: 4739
  md5: 6d531ebd6d6626b8d47ea98e91bfb06e
  page: blog__转载_异装癖？_Xavier杰斯君_-_新浪网站导航.md
- name: blog_“囧”还是“惊艳”，影视圈二十大雷人伪娘_图__吹雪_-_新浪网站导航
  filename: blog_“囧”还是“惊艳”，影视圈二十大雷人伪娘_图__吹雪_-_新浪网站导航.md
  type: webpage
  format: Markdown
  size: 4853
  md5: ec439880410e1a10922916ad152894a1
  page: blog_“囧”还是“惊艳”，影视圈二十大雷人伪娘_图__吹雪_-_新浪网站导航.md
- name: blog_东南亚观光——（五）七律观泰国人妖有感
  filename: blog_东南亚观光——（五）七律观泰国人妖有感.md
  type: webpage
  format: Markdown
  size: 6599
  md5: 90a1dfad597851b167dd94eec6315f7a
  page: blog_东南亚观光——（五）七律观泰国人妖有感.md
- name: blog_北京变装会所燕子摄影师告诉你如何变装好看_-_新浪网站导航
  filename: blog_北京变装会所燕子摄影师告诉你如何变装好看_-_新浪网站导航.md
  type: webpage
  format: Markdown
  size: 10639
  md5: 2d03ed89397e1facbab52541754500c2
  page: blog_北京变装会所燕子摄影师告诉你如何变装好看_-_新浪网站导航.md
- name: blog_双性人小说1_郁郁_-_新浪网站导航
  filename: blog_双性人小说1_郁郁_-_新浪网站导航.md
  type: webpage
  format: Markdown
  size: 4666
  md5: fcbc3eb00ed01f8c9c186dedddf57ce8
  page: blog_双性人小说1_郁郁_-_新浪网站导航.md
- name: blog_反串表演、伪娘、雌雄一体的区别_仙疯叨咕_-_新浪网站导航
  filename: blog_反串表演、伪娘、雌雄一体的区别_仙疯叨咕_-_新浪网站导航.md
  type: webpage
  format: Markdown
  size: 5717
  md5: d87cc271abf86e3c64f22bb5af3205b4
  page: blog_反串表演、伪娘、雌雄一体的区别_仙疯叨咕_-_新浪网站导航.md
- name: blog_变性人小说_他者女性：梅魇_-_新浪网站导航
  filename: blog_变性人小说_他者女性：梅魇_-_新浪网站导航.md
  type: webpage
  format: Markdown
  size: 2494
  md5: 34afcfdff4703a1beee453668cee34d8
  page: blog_变性人小说_他者女性：梅魇_-_新浪网站导航.md
- name: blog_异装癖_戏作三昧_-_新浪网站导航
  filename: blog_异装癖_戏作三昧_-_新浪网站导航.md
  type: webpage
  format: Markdown
  size: 4961
  md5: 8f10921b3b714f3dfaefcbef954f589e
  page: blog_异装癖_戏作三昧_-_新浪网站导航.md
- name: blog_柯倩婷_新浪博客-_性别酷儿
  filename: blog_柯倩婷_新浪博客-_性别酷儿.md
  type: webpage
  format: Markdown
  size: 2511
  md5: afbab43d9244fe32e544ab3710ee1651
  page: blog_柯倩婷_新浪博客-_性别酷儿.md
- name: blog_柯倩婷_新浪博客-_性别酷儿_1
  filename: blog_柯倩婷_新浪博客-_性别酷儿_1.md
  type: webpage
  format: Markdown
  size: 599
  md5: 5722d3e562e3e252d6334d9efec5044b
  page: blog_柯倩婷_新浪博客-_性别酷儿_1.md
- name: blog_自编小说_爱口罩_-_新浪网站导航
  filename: blog_自编小说_爱口罩_-_新浪网站导航.md
  type: webpage
  format: Markdown
  size: 5969
  md5: fc6a2c5403bba2e5e05aaf30c0c3f2aa
  page: blog_自编小说_爱口罩_-_新浪网站导航.md
- name: blog_西方文化_Trans雪精灵_新浪博客
  filename: blog_西方文化_Trans雪精灵_新浪博客.md
  type: webpage
  format: Markdown
  size: 2523
  md5: 600a4991aacc519039877c516ecc9b70
  page: blog_西方文化_Trans雪精灵_新浪博客.md
- name: doc_来来来我给你看个宝贝游戏中的女装大佬_-_新浪
  filename: doc_来来来我给你看个宝贝游戏中的女装大佬_-_新浪.md
  type: webpage
  format: Markdown
  size: 10124
  md5: 33902462cd34fdceaf54959517ca71fd
  page: doc_来来来我给你看个宝贝游戏中的女装大佬_-_新浪.md
- name: edu_cdts是什么意思的缩写_-_爱问教育
  filename: edu_cdts是什么意思的缩写_-_爱问教育.md
  type: webpage
  format: Markdown
  size: 5014
  md5: 93a655b1b340e4faba97c03b1371b7f7
  page: edu_cdts是什么意思的缩写_-_爱问教育.md
- name: edu_变装小说博客word_press（变装文学大全）_-_爱问教育
  filename: edu_变装小说博客word_press（变装文学大全）_-_爱问教育.md
  type: webpage
  format: Markdown
  size: 3315
  md5: f74d50212387a6ccbc12ac011ab5c0b3
  page: edu_变装小说博客word_press（变装文学大全）_-_爱问教育.md
- name: eladies_走近变性手术台_附图_
  filename: eladies_走近变性手术台_附图_.md
  type: webpage
  format: Markdown
  size: 10027
  md5: 75928c5f0614ef4a740d96dd5c8f366d
  page: eladies_走近变性手术台_附图_.md
- name: fj_第十届“嗓音医学新进展学习班”在厦召开_-_新浪福建
  filename: fj_第十届“嗓音医学新进展学习班”在厦召开_-_新浪福建.md
  type: webpage
  format: Markdown
  size: 3500
  md5: 8793fd5c5a0ef50bd6fcbc3dfa43d801
  page: fj_第十届“嗓音医学新进展学习班”在厦召开_-_新浪福建.md
- name: k_泰国最好看的人妖秀在哪看!最不可错过的是这8家!_-_新浪
  filename: k_泰国最好看的人妖秀在哪看!最不可错过的是这8家!_-_新浪.md
  type: webpage
  format: Markdown
  size: 14322
  md5: e7dcdb8ccb74f7bd4fa71d5af3e93545
  page: k_泰国最好看的人妖秀在哪看!最不可错过的是这8家!_-_新浪.md
- name: m_witch103_-_微博
  filename: m_witch103_-_微博.md
  type: webpage
  format: Markdown
  size: 9545
  md5: eb86935f55a2379d184f9db263414822
  page: m_witch103_-_微博.md
- name: news_50岁男子欲作变性手术妻子女儿表示支持_图_
  filename: news_50岁男子欲作变性手术妻子女儿表示支持_图_.md
  type: webpage
  format: Markdown
  size: 10450
  md5: 46e10f96c0ee6fac05bd4caa6ebb767e
  page: news_50岁男子欲作变性手术妻子女儿表示支持_图_.md
- name: news_“美容第一刀”被告手术毁容_图_
  filename: news_“美容第一刀”被告手术毁容_图_.md
  type: webpage
  format: Markdown
  size: 2287
  md5: 253b0283407a3356b477154f2a7e933f
  page: news_“美容第一刀”被告手术毁容_图_.md
- name: news_“蝴蝶妹妹”何嫱在广州华美整形美容医院进行了第二期变形手术
  filename: news_“蝴蝶妹妹”何嫱在广州华美整形美容医院进行了第二期变形手术.md
  type: webpage
  format: Markdown
  size: 5898
  md5: 5b49493923e2aee266eb32ff0f5a24cf
  page: news_“蝴蝶妹妹”何嫱在广州华美整形美容医院进行了第二期变形手术.md
- name: news_一刀下去，他变她30岁的亚男昨成功实施变性手术
  filename: news_一刀下去，他变她30岁的亚男昨成功实施变性手术.md
  type: webpage
  format: Markdown
  size: 4033
  md5: 1e72dfabdab0e2de575c7a2b321e9ef9
  page: news_一刀下去，他变她30岁的亚男昨成功实施变性手术.md
- name: news_全国女子长跑亚军昨成功进行变性手术_图__-_新浪新闻
  filename: news_全国女子长跑亚军昨成功进行变性手术_图__-_新浪新闻.md
  type: webpage
  format: Markdown
  size: 4461
  md5: 3427cf70b908175edf2e49c50a31a3f6
  page: news_全国女子长跑亚军昨成功进行变性手术_图__-_新浪新闻.md
- name: news_变性人参选美国议员
  filename: news_变性人参选美国议员.md
  type: webpage
  format: Markdown
  size: 3252
  md5: dcfbfa16d69aeb0a80ccefb47317c49e
  page: news_变性人参选美国议员.md
- name: news_变性后他当上合法丈夫_图_
  filename: news_变性后他当上合法丈夫_图_.md
  type: webpage
  format: Markdown
  size: 4395
  md5: 36b8bb82664b277df28acb5c94d6b680
  page: news_变性后他当上合法丈夫_图_.md
- name: news_新民周刊：变性男女的婚姻生活_图_
  filename: news_新民周刊：变性男女的婚姻生活_图_.md
  type: webpage
  format: Markdown
  size: 15640
  md5: 4cf3a46b52003eba39fc3450fe0caa95
  page: news_新民周刊：变性男女的婚姻生活_图_.md
- name: news_浙江25岁小伙圆“女人梦”_组图_
  filename: news_浙江25岁小伙圆“女人梦”_组图_.md
  type: webpage
  format: Markdown
  size: 3127
  md5: 51dc9e2dd31154f3e9f83843856a5e8f
  page: news_浙江25岁小伙圆“女人梦”_组图_.md
- name: news_特朗普欲再推变性人服役禁令美议员：十分丑陋
  filename: news_特朗普欲再推变性人服役禁令美议员：十分丑陋.md
  type: webpage
  format: Markdown
  size: 13090
  md5: b214df0a51be5fb3ccf811370acd6f0e
  page: news_特朗普欲再推变性人服役禁令美议员：十分丑陋.md
- name: news_阴阳人变性为男后无性能力再变性为女身_图_
  filename: news_阴阳人变性为男后无性能力再变性为女身_图_.md
  type: webpage
  format: Markdown
  size: 10861
  md5: 78697594ebda57983283ea63ddc0fe5b
  page: news_阴阳人变性为男后无性能力再变性为女身_图_.md
- name: news_马来“变性美女”嫁给帅哥_图_
  filename: news_马来“变性美女”嫁给帅哥_图_.md
  type: webpage
  format: Markdown
  size: 4363
  md5: 68553799cadce9cbfb10943af985bbf8
  page: news_马来“变性美女”嫁给帅哥_图_.md
- name: video_29岁小伙在泰国做完变性手术，回到湖北想变更户口性别_-_新浪视频
  filename: video_29岁小伙在泰国做完变性手术，回到湖北想变更户口性别_-_新浪视频.md
  type: webpage
  format: Markdown
  size: 618
  md5: 732f4a31fe4bc2d20fd72fc86a0a6993
  page: video_29岁小伙在泰国做完变性手术，回到湖北想变更户口性别_-_新浪视频.md
subdirs: []
