name: 中国新闻网
description: 本目录涉及多元性别主题的多篇报道，内容涵盖变性人、性别表现、儿童性心理等方面，展示了中性化以及性别多元化政策的发展。首先，讨论了韩国变性艺人河莉秀为改户口而向法院申请更改性别的经历，突显了个人与社会之间、公众形象与私生活之间的紧张关系；紧接着是四川泸州监察局调查官员公款观赏人妖表演事件的报道，揭示了公众对社会风气的强烈关注以及官员行为所引发的道德争议。之后，伦敦小学生交换妓女名片现象的报道引起了人们对儿童成长环境的担忧，政府对此的回应显示了社会和法律对性别暴露行为的态度。家庭背景对儿童性取向的影响也是本目录的一个重点，文章结合数据与心理学理论探讨性心理发展的复杂性，反映了社会对个体性取向误解的现状。同时，以日本女星中山美穗因丈夫的性别表现变化而引发的婚姻危机为例，进一步探讨现代婚姻中可能遇到的复杂性。除此之外，关于日本“伪娘”文化的分析展示了社会性别角色的演变，以及其对年轻人价值观的影响。最后，金色海岸变性人登记参选省议员的报导和美国海军解除对变性人服役禁令的消息，展现了多元性别群体在社会政治领域的新进展，体现了对变性人士权益的日渐重视与支持。
curator: ''
source: ''
tags:
- 变性人
- 性别表现
- 儿童性心理
- 河莉秀
- 泸州官员事件
- 伦敦小学生
- 性别多元化
- 家庭因素
- 中山美穗
- 伪娘文化
- 变性人参选
- 美军性别身份政策
license: ''
files:
- name: www_变性艺人河莉秀：为了私生活我要改户口！（图）
  filename: www_变性艺人河莉秀：为了私生活我要改户口！（图）.md
  type: webpage
  format: Markdown
  size: 2355
  md5: 87d1164b96707a72a8b9f347b4c5b5d3
  page: www_变性艺人河莉秀：为了私生活我要改户口！（图）.md
- name: www_四川泸州监察局介入调查官员公款看人妖事件_-_中国新闻网
  filename: www_四川泸州监察局介入调查官员公款看人妖事件_-_中国新闻网.md
  type: webpage
  format: Markdown
  size: 2770
  md5: 7817e5f39cb604f7f03b220e162ae207
  page: www_四川泸州监察局介入调查官员公款看人妖事件_-_中国新闻网.md
- name: www_图文；伦敦小学生流行交换妓女名片
  filename: www_图文；伦敦小学生流行交换妓女名片.md
  type: webpage
  format: Markdown
  size: 2519
  md5: e136665a7d87483b4061180aba0d2fe0
  page: www_图文；伦敦小学生流行交换妓女名片.md
- name: www_家庭因素影响孩子性取向_-_中国新闻网
  filename: www_家庭因素影响孩子性取向_-_中国新闻网.md
  type: webpage
  format: Markdown
  size: 5491
  md5: b09c6a2176e51531f18153f48323af48
  page: www_家庭因素影响孩子性取向_-_中国新闻网.md
- name: www_日女星中山美穗被曝离婚因不满老公人妖装扮_-_中国新闻网
  filename: www_日女星中山美穗被曝离婚因不满老公人妖装扮_-_中国新闻网.md
  type: webpage
  format: Markdown
  size: 1817
  md5: 460658925289c0d95042230591a507c7
  page: www_日女星中山美穗被曝离婚因不满老公人妖装扮_-_中国新闻网.md
- name: www_日本华媒：是什么让日本“伪娘”泛滥成灾？_-_中国新闻网
  filename: www_日本华媒：是什么让日本“伪娘”泛滥成灾？_-_中国新闻网.md
  type: webpage
  format: Markdown
  size: 3923
  md5: 6d786c2b9dce16367e464070c89e9bfd
  page: www_日本华媒：是什么让日本“伪娘”泛滥成灾？_-_中国新闻网.md
- name: www_泰国一名变性人登记参选省议员创该国首例_图_
  filename: www_泰国一名变性人登记参选省议员创该国首例_图_.md
  type: webpage
  format: Markdown
  size: 2190
  md5: 90a17fad425916c73685790be4b0f3a3
  page: www_泰国一名变性人登记参选省议员创该国首例_图_.md
- name: www_美军解除变性人服役禁令不再因性别身份区别对待
  filename: www_美军解除变性人服役禁令不再因性别身份区别对待.md
  type: webpage
  format: Markdown
  size: 2211
  md5: 085d5a1075c5e74237d736f363f2dc19
  page: www_美军解除变性人服役禁令不再因性别身份区别对待.md
subdirs: []
