name: 搜狐
description: ''
curator: ''
source: ''
tags: []
license: ''
files:
- name: mil_27岁帅哥军官变性成美女带兵超过100人_-_军事-_搜狐
  filename: mil_27岁帅哥军官变性成美女带兵超过100人_-_军事-_搜狐.md
  type: webpage
  format: Markdown
  size: 2336
  md5: 7e920df9359d5428378aba9c86d4804b
  page: mil_27岁帅哥军官变性成美女带兵超过100人_-_军事-_搜狐.md
- name: my_人妖rose_-_栏目_-_搜狐视频自媒体
  filename: my_人妖rose_-_栏目_-_搜狐视频自媒体.md
  type: webpage
  format: Markdown
  size: 12917
  md5: 34ba39e70da624d91169886cd9f94aa4
  page: my_人妖rose_-_栏目_-_搜狐视频自媒体.md
- name: my_变性人-_栏目_-_搜狐视频
  filename: my_变性人-_栏目_-_搜狐视频.md
  type: webpage
  format: Markdown
  size: 6369
  md5: 615d40a438784feb539f1b1bc88b2f13
  page: my_变性人-_栏目_-_搜狐视频.md
- name: news_'我天生就应做女人'_一个阴阳人的变性故事_组图__-_新闻-_搜狐
  filename: news_'我天生就应做女人'_一个阴阳人的变性故事_组图__-_新闻-_搜狐.md
  type: webpage
  format: Markdown
  size: 5750
  md5: 1a172154e795f3b6b3c67b56f178736e
  page: news_'我天生就应做女人'_一个阴阳人的变性故事_组图__-_新闻-_搜狐.md
- name: news_28岁两性畸形人性别难辨无法办身份证户籍_图__-_新闻-_搜狐
  filename: news_28岁两性畸形人性别难辨无法办身份证户籍_图__-_新闻-_搜狐.md
  type: webpage
  format: Markdown
  size: 5472
  md5: 3f275c9dc4c4b14b8c660e9e50818bc0
  page: news_28岁两性畸形人性别难辨无法办身份证户籍_图__-_新闻-_搜狐.md
- name: news_“中国变性第一人”--张克莎中山签名售书_图__-_新闻-_搜狐
  filename: news_“中国变性第一人”--张克莎中山签名售书_图__-_新闻-_搜狐.md
  type: webpage
  format: Markdown
  size: 3964
  md5: ead5ef979fbef0c7f64e0c8a9ef2cf41
  page: news_“中国变性第一人”--张克莎中山签名售书_图__-_新闻-_搜狐.md
- name: news_中国变性人-新闻频道_-_搜狐
  filename: news_中国变性人-新闻频道_-_搜狐.md
  type: webpage
  format: Markdown
  size: 10083
  md5: 04c2aadc085bfc57cb0c96ac19509bf2
  page: news_中国变性人-新闻频道_-_搜狐.md
- name: news_假若性别消失_-_新闻-_搜狐
  filename: news_假若性别消失_-_新闻-_搜狐.md
  type: webpage
  format: Markdown
  size: 12021
  md5: e9df6c9e2d89fab998c4829fb929f0a0
  page: news_假若性别消失_-_新闻-_搜狐.md
- name: news_医学博士：想变性难于上清华北大_图__-_新闻-_搜狐
  filename: news_医学博士：想变性难于上清华北大_图__-_新闻-_搜狐.md
  type: webpage
  format: Markdown
  size: 9806
  md5: de747e781c8a197295eae28148a7679d
  page: news_医学博士：想变性难于上清华北大_图__-_新闻-_搜狐.md
- name: news_变性新闻-新闻频道_-_搜狐
  filename: news_变性新闻-新闻频道_-_搜狐.md
  type: webpage
  format: Markdown
  size: 11252
  md5: 3a34814912bfbaeff8f1d4b294967fa9
  page: news_变性新闻-新闻频道_-_搜狐.md
- name: news_变性美女陈莉莉福州征婚曾经为情而自杀_组图__-搜狐新闻
  filename: news_变性美女陈莉莉福州征婚曾经为情而自杀_组图__-搜狐新闻.md
  type: webpage
  format: Markdown
  size: 1758
  md5: 28dbd5ac276fb099d9ef1c6ba2a15d84
  page: news_变性美女陈莉莉福州征婚曾经为情而自杀_组图__-搜狐新闻.md
- name: news_图文：变性人陈莉莉福州再次动刀完善女性特征_-_新闻-_搜狐
  filename: news_图文：变性人陈莉莉福州再次动刀完善女性特征_-_新闻-_搜狐.md
  type: webpage
  format: Markdown
  size: 1236
  md5: 7c8c328e4c7cb3976cda06b24e05d4c5
  page: news_图文：变性人陈莉莉福州再次动刀完善女性特征_-_新闻-_搜狐.md
- name: news_孕妇乘上公交车竟然无人让座位-搜狐新闻中心
  filename: news_孕妇乘上公交车竟然无人让座位-搜狐新闻中心.md
  type: webpage
  format: Markdown
  size: 1437
  md5: 151532868c5ca3d98562609e20049588
  page: news_孕妇乘上公交车竟然无人让座位-搜狐新闻中心.md
- name: news_曾经变性人，今为爱再度上手术台_-_搜狐
  filename: news_曾经变性人，今为爱再度上手术台_-_搜狐.md
  type: webpage
  format: Markdown
  size: 10647
  md5: 2f9b302b62f295e48567c266d01a9b1f
  page: news_曾经变性人，今为爱再度上手术台_-_搜狐.md
- name: news_缅甸女一夜变男人长出男性生殖器乳房消失_图_-搜狐新闻中心
  filename: news_缅甸女一夜变男人长出男性生殖器乳房消失_图_-搜狐新闻中心.md
  type: webpage
  format: Markdown
  size: 3096
  md5: c3173eca87007ecf484a647158627dff
  page: news_缅甸女一夜变男人长出男性生殖器乳房消失_图_-搜狐新闻中心.md
- name: news_贵州男子变性当美女_图__-_新闻-_搜狐
  filename: news_贵州男子变性当美女_图__-_新闻-_搜狐.md
  type: webpage
  format: Markdown
  size: 933
  md5: 51d14df02dd7ca53b61a48c326aad950
  page: news_贵州男子变性当美女_图__-_新闻-_搜狐.md
- name: news_韩国大法院首次许可变性人更改户籍性别_-_新闻-_搜狐
  filename: news_韩国大法院首次许可变性人更改户籍性别_-_新闻-_搜狐.md
  type: webpage
  format: Markdown
  size: 8286
  md5: ddd3988f110ab5add0f1c36b00cb11d0
  page: news_韩国大法院首次许可变性人更改户籍性别_-_新闻-_搜狐.md
- name: pic_高清图：阿根廷美女裹胸秀性感伪娘着芭蕾舞裙_121_
  filename: pic_高清图：阿根廷美女裹胸秀性感伪娘着芭蕾舞裙_121_.md
  type: webpage
  format: Markdown
  size: 3956
  md5: cd3265316808c8b21b8c34bc43a2e6aa
  page: pic_高清图：阿根廷美女裹胸秀性感伪娘着芭蕾舞裙_121_.md
- name: sports_NCAA女篮球员欲不变性跨性别参赛已或学校支持_-_体育
  filename: sports_NCAA女篮球员欲不变性跨性别参赛已或学校支持_-_体育.md
  type: webpage
  format: Markdown
  size: 3775
  md5: 26a7e14c77a6a0bb776f51245798b06e
  page: sports_NCAA女篮球员欲不变性跨性别参赛已或学校支持_-_体育.md
- name: sports_结束25年男足经历澳大利亚变性人转投女足联赛_-_体育-_搜狐
  filename: sports_结束25年男足经历澳大利亚变性人转投女足联赛_-_体育-_搜狐.md
  type: webpage
  format: Markdown
  size: 2049
  md5: 343f24ca153e60f93ebd65b7a0e5028a
  page: sports_结束25年男足经历澳大利亚变性人转投女足联赛_-_体育-_搜狐.md
- name: tv_千万别看魔改三国动漫，天然呆吕布战力爆表，女子龙居然被一击秒
  filename: tv_千万别看魔改三国动漫，天然呆吕布战力爆表，女子龙居然被一击秒.md
  type: webpage
  format: Markdown
  size: 6123
  md5: 1523551154c004867db2497a8e1ec990
  page: tv_千万别看魔改三国动漫，天然呆吕布战力爆表，女子龙居然被一击秒.md
- name: tv_电影：杀千刀的人妖2010_-_搜狐视频
  filename: tv_电影：杀千刀的人妖2010_-_搜狐视频.md
  type: webpage
  format: Markdown
  size: 5787
  md5: 53bbe55b420672f2e156d38bcba24dfd
  page: tv_电影：杀千刀的人妖2010_-_搜狐视频.md
- name: tv_电影：跨性别名单2016_-_搜狐视频
  filename: tv_电影：跨性别名单2016_-_搜狐视频.md
  type: webpage
  format: Markdown
  size: 4115
  md5: 6916a8cecf04d64e103bb2d4ba91d217
  page: tv_电影：跨性别名单2016_-_搜狐视频.md
- name: v_视频：明星大考场戴军现场变身妩媚泰国人妖-搜狐娱乐播报
  filename: v_视频：明星大考场戴军现场变身妩媚泰国人妖-搜狐娱乐播报.md
  type: webpage
  format: Markdown
  size: 3878
  md5: 473fec4ec40a82a55cfd8fa6311026a9
  page: v_视频：明星大考场戴军现场变身妩媚泰国人妖-搜狐娱乐播报.md
- name: www_异装癖的女人和男人心理_-_搜狐
  filename: www_异装癖的女人和男人心理_-_搜狐.md
  type: webpage
  format: Markdown
  size: 4085
  md5: 53b3f893b349cba4d6c2a8da58a4d820
  page: www_异装癖的女人和男人心理_-_搜狐.md
- name: www_走异性的路让异性无路可走？6部跨性别经典电影_-_搜狐
  filename: www_走异性的路让异性无路可走？6部跨性别经典电影_-_搜狐.md
  type: webpage
  format: Markdown
  size: 6794
  md5: 1c95826d95970a4464c3e3572ad51d8f
  page: www_走异性的路让异性无路可走？6部跨性别经典电影_-_搜狐.md
- name: yule_娱乐频道-搜狐
  filename: yule_娱乐频道-搜狐.md
  type: webpage
  format: Markdown
  size: 12377
  md5: 3efa90799e7a978ddcabe1c96f7298ee
  page: yule_娱乐频道-搜狐.md
subdirs: []
